[build]
  publish = "."
  command = ""
  ignore = "echo 'Ignoring docs'"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = ""

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[ignore_files]]
  files = ["docs/*"]
